# Generated by Django 3.0.3 on 2020-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Day of the event', verbose_name='Date')),
                ('start_time', models.TimeField(help_text='Start time', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='End time', verbose_name='End Time')),
                ('reason', models.TextField(blank=True, help_text='Reason for the call', null=True, verbose_name='Reason')),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
            },
        ),
    ]
