# Generated by Django 3.0.3 on 2020-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_calendarevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='reason',
            field=models.TextField(default='test', help_text='Reason for the call', verbose_name='Reason'),
            preserve_default=False,
        ),
    ]
